// src/LazyImage.vue
<template>
    <div
      ref="containerRef"
      :class="['image-optimize-container', className]"
      :style="containerStyle"
      :data-id="dataId"
    >
      <!-- 占位符 -->
      <div v-if="showPlaceholder" class="image-optimize-placeholder">
        <svg
          v-if="showPlaceholderIcon"
          class="image-optimize-placeholder-icon"
          width="24"
          height="24"
          viewBox="0 0 24 24"
          fill="none"
          xmlns="http://www.w3.org/2000/svg"
        >
          <path
            d="M19 3H5C3.9 3 3 3.9 3 5V19C3 20.1 3.9 21 5 21H19C20.1 21 21 20.1 21 19V5C21 3.9 20.1 3 19 3ZM19 19H5V5H19V19ZM13.96 12.29L11.21 15.83L9.25 13.47L6.5 17H17.5L13.96 12.29Z"
            fill="currentColor"
          />
        </svg>
      </div>
  
      <!-- 加载中 -->
      <div v-if="showLoading" class="image-optimize-loading">
        <svg
          class="image-optimize-loading-icon"
          width="24"
          height="24"
          viewBox="0 0 24 24"
          fill="none"
          xmlns="http://www.w3.org/2000/svg"
        >
          <circle
            cx="12"
            cy="12"
            r="10"
            stroke="currentColor"
            stroke-width="2"
            fill="none"
            stroke-dasharray="62.83"
            stroke-dashoffset="31.42"
          />
        </svg>
        <span v-if="isCompressing" class="compressing-text">
          正在压缩图片...
        </span>
      </div>
  
      <!-- 实际图片 -->
      <img
        v-if="shouldLoad && optimizedSrc"
        ref="imgRef"
        :src="optimizedSrc"
        :alt="alt"
        :class="['image-optimize-image', imageClassName]"
        :style="computedImageStyle"
        @load="handleLoad"
        @error="handleError"
        @click="handleClick"
      />
  
      <!-- 错误占位符 -->
      <div v-if="hasError" class="image-optimize-error">
        <svg
          class="image-optimize-error-icon"
          width="24"
          height="24"
          viewBox="0 0 24 24"
          fill="none"
          xmlns="http://www.w3.org/2000/svg"
        >
          <path
            d="M19 3H5C3.9 3 3 3.9 3 5V19C3 20.1 3.9 21 5 21H19C20.1 21 21 20.1 21 19V5C21 3.9 20.1 3 19 3ZM19 19H5V5H19V19Z"
            fill="currentColor"
          />
        </svg>
        <span v-if="showErrorMessage" class="image-optimize-error-text">
          加载失败
        </span>
      </div>
    </div>
  </template>
  
  <script>
import { 
  optimizeImageUrl, 
  compareImageSizes, 
  detectCDN,
  compressImageInBrowser,
  dataURLToBlob,
  formatFileSize,
  generateBlurPlaceholderUrl,
} from '../lib/imageOptimize.js';
import { loadImageWithCache, loadImageProgressiveWithCache, setCache } from '../lib/imageCache.js';
import './LazyImage.css';
  
  export default {
    name: 'LazyImage',
    
    props: {
      src: {
        type: String,
        default: ''
      },
      alt: {
        type: String,
        default: ''
      },
      width: {
        type: [String, Number],
        default: '100%'
      },
      height: {
        type: [String, Number],
        default: 'auto'
      },
      className: {
        type: String,
        default: ''
      },
      imageClassName: {
        type: String,
        default: ''
      },
      dataId: {
        type: [String, Number],
        default: null
      },
      imageStyle: {
        type: Object,
        default: () => ({})
      },
      immediate: {
        type: Boolean,
        default: false
      },
      rootMargin: {
        type: String,
        default: '50px'
      },
      optimize: {
        type: Object,
        default: () => ({
          width: 240,
          height: 320,
          quality: 30
        })
      },
      enableBrowserCompression: {
        type: Boolean,
        default: true
      },
      showPlaceholderIcon: {
        type: Boolean,
        default: false
      },
      showErrorMessage: {
        type: Boolean,
        default: false
      },
      errorSrc: {
        type: String,
        default: null
      },
      progressive: {
        type: Boolean,
        default: false
      },
      progressiveStages: {
        type: Array,
        default: () => [
          { width: 20, quality: 20, blur: 10 },
          { width: 400, quality: 50, blur: 3 },
          { width: null, quality: 80, blur: 0 }
        ]
      },
      progressiveTransitionDuration: {
        type: Number,
        default: 300
      },
      progressiveTimeout: {
        type: Number,
        default: 30000
      },
      progressiveEnableCache: {
        type: Boolean,
        default: true
      }
    },
  
    emits: ['load', 'optimization', 'error', 'click', 'progressive-stage-complete'],
  
    data() {
      return {
        isLoaded: false,
        isLoading: false,
        hasError: false,
        shouldLoad: this.immediate,
        lockedSrc: '',
        compressedSrc: null,
        isCompressing: false,
        cachedBlobUrl: null,
        progressiveStageIndex: -1,
        progressiveImageUrl: '',
        observer: null,
        optimizationInfo: null
      };
    },
  
    computed: {
      containerStyle() {
        return {
          width: typeof this.width === 'number' ? `${this.width}px` : this.width,
          height: typeof this.height === 'number' ? `${this.height}px` : this.height
        };
      },
  
      showPlaceholder() {
        return !this.isLoaded && !this.hasError && !this.isLoading && 
               !this.cachedBlobUrl && !this.progressiveImageUrl;
      },
  
      showLoading() {
        return (this.isLoading || this.isCompressing) && !this.hasError && 
               !this.cachedBlobUrl && !this.progressiveImageUrl;
      },
  
      optimizedSrc() {
        if (!this.src) return '';
  
        // 渐进式加载优先
        if (this.progressive && this.progressiveImageUrl) {
          return this.progressiveImageUrl;
        }
  
        // 浏览器端压缩图片
        if (this.compressedSrc) {
          return this.compressedSrc;
        }
  
        // 缓存图片
        if (this.cachedBlobUrl) {
          return this.cachedBlobUrl;
        }
  
        if (this.isLoaded && this.lockedSrc) {
          return this.lockedSrc;
        }
  
        return this.getOptimizedUrl(this.src);
      },
  
      computedImageStyle() {
        const baseStyle = {
          display: this.isLoaded || this.cachedBlobUrl || this.progressiveImageUrl || 
                  (!this.hasError && this.optimizedSrc) ? 'block' : 'none',
          ...this.imageStyle
        };
  
        if (this.progressive) {
          baseStyle.transition = `opacity ${this.progressiveTransitionDuration}ms ease-in-out, filter ${this.progressiveTransitionDuration}ms ease-in-out`;
          baseStyle.opacity = this.progressiveStageIndex >= 0 ? 1 : 
                            (this.isLoaded || this.cachedBlobUrl ? 1 : 0);
          
          // 渐进式模糊效果
          baseStyle.filter = this.progressiveStageIndex === 1 ? 'blur(10px)' :
                            this.progressiveStageIndex === 2 ? 'blur(3px)' :
                            this.progressiveStageIndex >= 3 ? 'blur(0px)' : 'blur(10px)';
        }
  
        return baseStyle;
      }
    },
  
    watch: {
      src: {
        handler(newSrc, oldSrc) {
          if (newSrc !== oldSrc) {
            this.resetState();
            if (this.immediate) {
              this.shouldLoad = true;
            } else {
              this.initObserver();
            }
          }
        },
        immediate: true
      },
  
      shouldLoad: {
        handler(newVal) {
          if (newVal && this.progressive) {
            this.handleProgressiveLoad();
          } else if (newVal && !this.progressive) {
            this.handleShouldLoad();
          }
        },
        immediate: true
      }
    },
    methods: {
    // 获取优化后的URL
    getOptimizedUrl(imageSrc) {
      if (!imageSrc) return '';
      try {
        if (this.optimize && Object.keys(this.optimize).length > 0) {
          const optimized = optimizeImageUrl(imageSrc, this.optimize);
          if (optimized && optimized.trim()) {
            return optimized;
          }
        }
        return imageSrc;
      } catch (error) {
        console.warn('图片URL优化失败，使用原始URL:', error);
        return imageSrc;
      }
    },

    // 初始化 Intersection Observer
    initObserver() {
      if (this.immediate || typeof window === 'undefined' || !window.IntersectionObserver) {
        this.shouldLoad = true;
        return;
      }

      // 清理现有的 observer
      if (this.observer) {
        this.observer.disconnect();
        this.observer = null;
      }

      this.observer = new IntersectionObserver(
        (entries) => {
          entries.forEach((entry) => {
            if (entry.isIntersecting) {
              this.shouldLoad = true;
              if (this.observer && entry.target) {
                this.observer.unobserve(entry.target);
              }
            }
          });
        },
        {
          rootMargin: this.rootMargin,
          threshold: 0.01
        }
      );

      // 等待 DOM 更新后再观察
      this.$nextTick(() => {
        if (this.$refs.containerRef && this.observer) {
          this.observer.observe(this.$refs.containerRef);
        }
      });
    },

    // 处理图片加载成功
    async handleLoad(event) {
      const currentSrc = event.target.src;
      
      // 渐进式加载时，只有在最后一个阶段才标记为已加载
      if (this.progressive) {
        // 如果是渐进式加载的最后一个阶段，才标记为已加载
        if (this.progressiveStageIndex >= this.progressiveStages.length) {
          if (this.isLoaded) return;
          this.isLoaded = true;
          this.isLoading = false;
          this.hasError = false;
          this.lockedSrc = currentSrc;
        } else {
          // 中间阶段：更新状态但不标记为完全加载，允许继续加载下一阶段
          this.isLoading = false;
          this.hasError = false;
          // 不设置 isLoaded，允许继续加载下一阶段
          return;
        }
      } else {
        if (this.isLoaded) return;
        this.isLoaded = true;
        this.isLoading = false;
        this.hasError = false;
        this.lockedSrc = currentSrc;
      }

      // 保存到缓存
      if (!currentSrc.startsWith('blob:') && !currentSrc.startsWith('data:')) {
        try {
          const finalUrl = this.getOptimizedUrl(this.src);
          const response = await fetch(finalUrl);
          if (response.ok) {
            const arrayBuffer = await response.arrayBuffer();
            const imageData = new Uint8Array(arrayBuffer);
            const mimeType = response.headers.get('Content-Type') || 'image/jpeg';
            
            const binaryString = String.fromCharCode.apply(null, Array.from(imageData));
            const base64String = btoa(binaryString);
            const dataUrl = `data:${mimeType};base64,${base64String}`;
            
            const cacheKey = `image:${finalUrl}`;
            await setCache(cacheKey, { data: dataUrl, mimeType });
          }
        } catch (error) {
          console.warn('保存图片缓存失败:', error);
        }
      }

      // 获取优化信息
      let optimizationInfo = null;
      if (this.src && currentSrc !== this.src) {
        try {
          const comparison = await compareImageSizes(this.src, currentSrc);
          if (comparison.originalSize !== null && comparison.optimizedSize !== null) {
            optimizationInfo = {
              originalUrl: comparison.originalUrl,
              originalSize: comparison.originalSize,
              originalSizeFormatted: comparison.originalSizeFormatted,
              optimizedUrl: comparison.optimizedUrl,
              optimizedSize: comparison.optimizedSize,
              optimizedSizeFormatted: comparison.optimizedSizeFormatted,
              savedSize: comparison.savedSize,
              savedSizeFormatted: comparison.savedSizeFormatted,
              savedPercentage: comparison.savedPercentage,
              cdn: comparison.cdn,
              isOptimizationEffective: comparison.isOptimizationEffective,
              warningMessage: comparison.warningMessage,
            };
            
            this.optimizationInfo = optimizationInfo;
            this.$emit('optimization', optimizationInfo);
          }
        } catch (error) {
          console.warn('获取图片大小对比失败:', error);
        }
      }

      this.$emit('load', event, optimizationInfo);
    },

    // 处理图片加载失败
    handleError(event) {
      if (this.isLoaded) return;

      const currentSrc = event.target.src;
      const optimizedUrl = this.getOptimizedUrl(this.src);

      if (this.errorSrc && (currentSrc === this.errorSrc || currentSrc.includes('videoCover.png'))) {
        this.hasError = true;
        this.isLoading = false;
        this.$emit('error', event);
        return;
      }

      if (currentSrc === optimizedUrl && optimizedUrl !== this.src) {
        event.target.src = this.src;
        return;
      }

      if (currentSrc === this.src || optimizedUrl === this.src) {
        if (this.errorSrc && currentSrc !== this.errorSrc) {
          event.target.src = this.errorSrc;
          return;
        }

        this.hasError = true;
        this.isLoading = false;
        this.$emit('error', event);
      }
    },

    // 处理图片点击
    handleClick(event) {
      const imageInfo = {
        src: this.src,
        currentSrc: event.target?.src || this.optimizedSrc,
        optimizedSrc: this.optimizedSrc,
        alt: this.alt,
        dataId: this.dataId,
        isLoaded: this.isLoaded,
        isLoading: this.isLoading,
        hasError: this.hasError,
        isCompressing: this.isCompressing,
        optimizationInfo: this.optimizationInfo,
        imageElement: event.target,
      };
      
      this.$emit('click', event, imageInfo);
    },

    // 处理渐进式加载
    async handleProgressiveLoad() {
      if (!this.progressive || this.isLoaded || this.hasError || 
          this.progressiveImageUrl || !this.src) {
        return;
      }

      try {
        this.isLoading = true;
        
        const result = await loadImageProgressiveWithCache(this.src, {
          stages: this.progressiveStages,
          timeout: this.progressiveTimeout,
          enableCache: this.progressiveEnableCache,
          onStageComplete: (stageIndex, stageUrl, stage) => {
            this.progressiveStageIndex = stageIndex + 1;
            this.progressiveImageUrl = stageUrl;
            this.$emit('progressive-stage-complete', stageIndex, stageUrl, stage);
          },
          onComplete: (finalUrl) => {
            this.progressiveImageUrl = finalUrl;
            this.progressiveStageIndex = this.progressiveStages.length;
            this.isLoading = false;
            // 图片元素的 load 事件会在 src 更新后自动触发
          },
          onError: (error, stageIndex) => {
            console.warn('渐进式加载失败:', error);
            this.isLoading = false;
            this.hasError = true;
            this.$emit('error', { error, stageIndex });
          }
        });

        if (result && result.url) {
          this.progressiveImageUrl = result.url;
          if (result.stages && result.stages.length > 0) {
            this.progressiveStageIndex = result.stages.length;
          }
        }
      } catch (error) {
        console.error('渐进式加载出错:', error);
        this.isLoading = false;
        this.hasError = true;
        this.$emit('error', { error });
      }
    },

    // 处理 shouldLoad 变化
    async handleShouldLoad() {
      if (this.progressive || this.isLoaded || this.hasError || this.isLoading || 
          this.isCompressing || this.cachedBlobUrl || this.progressiveImageUrl || !this.src) {
        return;
      }

      // 先尝试从缓存加载
      try {
        const finalUrl = this.getOptimizedUrl(this.src);
        const blobUrl = await loadImageWithCache(finalUrl);
        if (blobUrl) {
          this.cachedBlobUrl = blobUrl;
          return;
        }
      } catch (error) {
        // 缓存加载失败，继续正常流程
      }

      // 检查是否需要浏览器端压缩
      const cdn = detectCDN(this.src);
      const shouldUseBrowserCompression = 
        this.enableBrowserCompression && 
        !cdn && 
        this.optimize && Object.keys(this.optimize).length > 0 &&
        typeof window !== 'undefined' &&
        !this.compressedSrc;

      if (shouldUseBrowserCompression) {
        this.isCompressing = true;
        // 这里需要实现 compressImageInBrowser 函数
        // compressImageInBrowser(this.src, this.optimize)
        //   .then((dataURL) => {
        //     this.compressedSrc = dataURL;
        //     this.isCompressing = false;
        //   })
        //   .catch((error) => {
        //     console.warn('浏览器端压缩失败:', error);
        //     this.isCompressing = false;
        //     this.isLoading = true;
        //   });
      } else {
        this.isLoading = true;
      }
    },

    // 重置状态
    resetState() {
      // 清理 Blob URL
      if (this.cachedBlobUrl) {
        URL.revokeObjectURL(this.cachedBlobUrl);
      }

      this.isLoaded = false;
      this.hasError = false;
      this.isLoading = false;
      this.lockedSrc = '';
      this.compressedSrc = null;
      this.isCompressing = false;
      this.cachedBlobUrl = null;
      this.progressiveImageUrl = '';
      this.progressiveStageIndex = -1;
      this.optimizationInfo = null;
    }
  },

  mounted() {
    if (!this.immediate) {
      this.initObserver();
    } else {
      this.shouldLoad = true;
    }
  },

  beforeUnmount() {
    if (this.observer) {
      this.observer.disconnect();
      this.observer = null;
    }

    // 清理 Blob URL
    if (this.cachedBlobUrl) {
      URL.revokeObjectURL(this.cachedBlobUrl);
    }
  }
};
</script>
<style scoped>
@import './LazyImage.css';
</style>

// src/LazyImage.jsx
import React, { useEffect, useRef, useState, useMemo } from 'react';
import { 
  optimizeImageUrl, 
  compareImageSizes, 
  detectCDN,
  compressImageInBrowser,
  dataURLToBlob,
  formatFileSize,
} from '../lib/imageOptimize.js';
import { loadImageWithCache, saveImageCache } from './imageCache.js';
import './LazyImage.css';

/**
 * LazyImage 组件 - 支持懒加载和图片优化的图片组件
 * @param {Object} props - 组件属性
 * @param {string} props.src - 原始图片URL
 * @param {string} props.alt - 图片alt文本
 * @param {string|number} props.width - 容器宽度
 * @param {string|number} props.height - 容器高度
 * @param {string} props.className - 容器类名
 * @param {string} props.imageClassName - 图片类名
 * @param {string|number} props.dataId - data-id属性
 * @param {Object} props.imageStyle - 图片样式
 * @param {boolean} props.immediate - 是否立即加载（不懒加载）
 * @param {string} props.rootMargin - 懒加载根边距（提前加载的距离）
 * @param {Object} props.optimize - 图片优化选项
 * @param {number} props.optimize.compressionLevel - 压缩程度（0-1，默认0.5，0=不压缩，1=最大压缩）
 * @param {number} props.optimize.blur - 模糊程度（0-10，默认0，值越大越模糊）
 * @param {boolean} props.optimize.smooth - 是否启用图像平滑（默认true）
 * @param {boolean} props.enableBrowserCompression - 当CDN不支持优化时，是否启用浏览器端压缩（默认true）
 * @param {boolean} props.showPlaceholderIcon - 是否显示占位符图标
 * @param {boolean} props.showErrorMessage - 是否显示错误信息
 * @param {string|null} props.errorSrc - 错误时的默认图片（可选，如果为null则不加载错误图片，直接显示错误占位符）
 * @param {Function} props.onLoad - 加载成功回调 (event, optimizationInfo) - optimizationInfo包含优化信息
 * @param {Function} props.onOptimization - 优化完成回调 (optimizationInfo) - 专门用于接收优化信息
 * @param {Function} props.onError - 加载失败回调
 * @param {Function} props.onClick - 点击回调 (event, imageInfo) - imageInfo包含图片相关信息
 */
export default function LazyImage({
  src = '',
  alt = '',
  width = '100%',
  height = 'auto',
  className = '',
  imageClassName = '',
  dataId = null,
  imageStyle = {},
  immediate = false,
  rootMargin = '50px',
  optimize = {
    width: 240,
    height: 320,
    quality: 30,
  },
  enableBrowserCompression = true, // 默认启用浏览器端压缩
  showPlaceholderIcon = false,
  showErrorMessage = false,
  errorSrc = null, // 默认为 null，不加载错误图片，直接显示错误占位符
  onLoad = null,
  onOptimization = null, // 优化完成回调
  onError = null,
  onClick = null,
}) {
  const imgRef = useRef(null);
  const containerRef = useRef(null);
  const observerRef = useRef(null);
  const optimizationInfoRef = useRef(null); // 存储优化信息，供 onClick 使用
  const [isLoaded, setIsLoaded] = useState(false);
  const [isLoading, setIsLoading] = useState(false);
  const [hasError, setHasError] = useState(false);
  const [shouldLoad, setShouldLoad] = useState(immediate);
  const [lockedSrc, setLockedSrc] = useState('');
  const [compressedSrc, setCompressedSrc] = useState(null); // 浏览器端压缩后的图片
  const [isCompressing, setIsCompressing] = useState(false);
  const [cachedBlobUrl, setCachedBlobUrl] = useState(null); // 缓存的 Blob URL
  const cachedBlobUrlRef = useRef(null); // 用于清理 Blob URL

  // 获取优化后的URL
  const getOptimizedUrl = (imageSrc) => {
    if (!imageSrc) return '';
    try {
      if (optimize && Object.keys(optimize).length > 0) {
        const optimized = optimizeImageUrl(imageSrc, optimize);
        if (optimized && optimized.trim()) {
          return optimized;
        }
      }
      return imageSrc;
    } catch (error) {
      console.warn('图片URL优化失败，使用原始URL:', error);
      return imageSrc;
    }
  };

  // 优化后的图片URL
  const optimizedSrc = useMemo(() => {
    if (!src) return '';
    
    // 如果已经有浏览器端压缩的图片，优先使用
    if (compressedSrc) {
      return compressedSrc;
    }
    
    // 如果有缓存的 Blob URL，优先使用
    if (cachedBlobUrl) {
      return cachedBlobUrl;
    }
    
    if (isLoaded && lockedSrc) {
      return lockedSrc;
    }
    
    return getOptimizedUrl(src);
  }, [src, isLoaded, lockedSrc, optimize, compressedSrc, cachedBlobUrl]);

  // 初始化 Intersection Observer
  const initObserver = () => {
    if (immediate || typeof window === 'undefined' || !window.IntersectionObserver) {
      setShouldLoad(true);
      return;
    }

    // 如果已经有 observer，先清理
    if (observerRef.current) {
      observerRef.current.disconnect();
      observerRef.current = null;
    }

    observerRef.current = new IntersectionObserver(
      (entries) => {
        entries.forEach((entry) => {
          if (entry.isIntersecting) {
            setShouldLoad(true);
            // 只 unobserve 当前元素，不要 disconnect 整个 observer
            if (observerRef.current && entry.target) {
              observerRef.current.unobserve(entry.target);
            }
          }
        });
      },
      {
        rootMargin,
        threshold: 0.01,
      }
    );

    // 等待 DOM 更新后再观察
    setTimeout(() => {
      if (containerRef.current && observerRef.current) {
        observerRef.current.observe(containerRef.current);
      }
    }, 0);
  };

  // 处理图片加载成功
  const handleLoad = async (event) => {
    if (isLoaded) {
      return;
    }
    
    const currentSrc = event.target.src;
    setIsLoaded(true);
    setIsLoading(false);
    setHasError(false);
    setLockedSrc(currentSrc);
    
    // 如果不是从缓存加载的（不是 Blob URL），则保存到缓存
    if (!currentSrc.startsWith('blob:') && !currentSrc.startsWith('data:')) {
      try {
        const finalUrl = getOptimizedUrl(src);
        const response = await fetch(finalUrl);
        if (response.ok) {
          const arrayBuffer = await response.arrayBuffer();
          const imageData = new Uint8Array(arrayBuffer);
          const mimeType = response.headers.get('Content-Type') || 'image/jpeg';
          await saveImageCache(finalUrl, imageData, mimeType);
        }
      } catch (error) {
        // 保存缓存失败，不影响图片显示
        console.warn('保存图片缓存失败:', error);
      }
    }
    
    // 获取优化信息并传递给回调
    let optimizationInfo = null;
    if (src && currentSrc !== src) {
      try {
        const comparison = await compareImageSizes(src, currentSrc);
        if (comparison.originalSize !== null && comparison.optimizedSize !== null) {
          // 构建优化信息对象
          optimizationInfo = {
            // 原始信息
            originalUrl: comparison.originalUrl,
            originalSize: comparison.originalSize,
            originalSizeFormatted: comparison.originalSizeFormatted,
            
            // 优化后信息
            optimizedUrl: comparison.optimizedUrl,
            optimizedSize: comparison.optimizedSize,
            optimizedSizeFormatted: comparison.optimizedSizeFormatted,
            
            // 节省信息
            savedSize: comparison.savedSize,
            savedSizeFormatted: comparison.savedSizeFormatted,
            savedPercentage: comparison.savedPercentage,
            
            // 其他信息
            cdn: comparison.cdn,
            isOptimizationEffective: comparison.isOptimizationEffective,
            warningMessage: comparison.warningMessage,
          };
          
          // 存储优化信息到 ref，供 onClick 使用
          optimizationInfoRef.current = optimizationInfo;
          
          // 调用优化完成回调
          if (onOptimization) {
            onOptimization(optimizationInfo);
          }
          
          // 控制台日志（已注释）
          // const groupTitle = comparison.isOptimizationEffective 
          //   ? `✅ 图片优化效果 - ${alt || '图片'}` 
          //   : `❌ 图片优化无效 - ${alt || '图片'}`;
          
          // console.group(groupTitle);
          // console.log('原始URL:', comparison.originalUrl);
          // console.log('优化URL:', comparison.optimizedUrl);
          if (comparison.cdn) {
            // console.log(`检测到的CDN: ${comparison.cdn}`);
          } else {
            // console.log('⚠️ 未检测到支持的CDN');
          }
          // console.log(`原始大小: ${comparison.originalSizeFormatted} (${comparison.originalSize} 字节)`);
          // console.log(`优化后大小: ${comparison.optimizedSizeFormatted} (${comparison.optimizedSize} 字节)`);
          // console.log(`节省大小: ${comparison.savedSizeFormatted} (${comparison.savedSize} 字节)`);
          // console.log(`节省比例: ${comparison.savedPercentage}%`);
          
          if (comparison.warningMessage) {
            console.warn(comparison.warningMessage);
          }
          
          if (!comparison.isOptimizationEffective) {
            // console.warn('💡 建议：');
            // if (!comparison.cdn) {
            //   console.warn('   1. 使用支持的CDN（阿里云OSS、腾讯云COS、七牛云、又拍云、AWS CloudFront）');
            //   console.warn('   2. 或者使用支持通用查询参数的图片服务');
            //   console.warn('   3. 或者设置 immediate={false} 并关闭 optimize 参数，使用原始URL');
            // } else {
            //   console.warn('   1. 检查CDN配置是否正确');
            //   console.warn('   2. 确认CDN服务是否支持图片处理功能');
            // }
          }
          
          // console.groupEnd();
        } else {
          // 即使无法获取大小，也提供基本信息
          optimizationInfo = {
            originalUrl: src,
            optimizedUrl: currentSrc,
            originalSize: null,
            originalSizeFormatted: null,
            optimizedSize: null,
            optimizedSizeFormatted: null,
            savedSize: null,
            savedSizeFormatted: null,
            savedPercentage: null,
            cdn: detectCDN(src),
            isOptimizationEffective: null,
            warningMessage: '⚠️ 无法获取图片大小（可能由于CORS限制）',
          };
          
          // 存储优化信息到 ref，供 onClick 使用
          optimizationInfoRef.current = optimizationInfo;
          
          if (onOptimization) {
            onOptimization(optimizationInfo);
          }
          
          // console.log('⚠️ 无法获取图片大小（可能由于CORS限制）');
          // console.log('原始URL:', src);
          // console.log('优化URL:', currentSrc);
        }
      } catch (error) {
        console.warn('获取图片大小对比失败:', error);
        
        // 即使出错也提供基本信息
        optimizationInfo = {
          originalUrl: src,
          optimizedUrl: currentSrc,
          originalSize: null,
          originalSizeFormatted: null,
          optimizedSize: null,
          optimizedSizeFormatted: null,
          savedSize: null,
          savedSizeFormatted: null,
          savedPercentage: null,
          cdn: detectCDN(src),
          isOptimizationEffective: null,
          warningMessage: `获取图片大小对比失败: ${error.message}`,
        };
        
        // 存储优化信息到 ref，供 onClick 使用
        optimizationInfoRef.current = optimizationInfo;
        
        if (onOptimization) {
          onOptimization(optimizationInfo);
        }
      }
    }
    
    // 调用 onLoad 回调，传递优化信息作为第二个参数
    if (onLoad) {
      onLoad(event, optimizationInfo);
    }
  };

  // 处理图片加载失败
  const handleError = (event) => {
    if (isLoaded) {
      return;
    }
    
    const currentSrc = event.target.src;
    const optimizedUrl = getOptimizedUrl(src);
    
    // 如果指定了 errorSrc 且当前加载的是错误图片本身，不再重试
    if (errorSrc && (currentSrc === errorSrc || currentSrc.includes('videoCover.png'))) {
      setHasError(true);
      setIsLoading(false);
      if (onError) {
        onError(event);
      }
      return;
    }
    
    // 如果当前加载的是优化后的URL，且与原始URL不同，先尝试加载原始URL
    if (currentSrc === optimizedUrl && optimizedUrl !== src) {
      console.log('优化URL加载失败，尝试原始URL:', src);
      event.target.src = src;
      return;
    }
    
    // 如果当前加载的是原始URL，加载失败
    if (currentSrc === src || optimizedUrl === src) {
      // 如果指定了 errorSrc，尝试加载错误图片
      if (errorSrc && currentSrc !== errorSrc) {
        console.log('原始URL加载失败，尝试加载错误图片:', errorSrc);
        event.target.src = errorSrc;
        return;
      }
      
      // 如果没有指定 errorSrc 或错误图片也加载失败，直接显示错误占位符
      console.log('图片加载失败，显示错误占位符');
      setHasError(true);
      setIsLoading(false);
      
      if (onError) {
        onError(event);
      }
    }
  };

  // 处理图片点击
  const handleClick = (event) => {
    if (onClick) {
      // 构建图片信息对象
      const imageInfo = {
        // 基本图片信息
        src: src,                              // 原始图片URL
        currentSrc: event.target?.src || optimizedSrc, // 当前加载的图片URL
        optimizedSrc: optimizedSrc,           // 优化后的URL
        alt: alt,                              // 图片alt文本
        dataId: dataId,                        // data-id属性
        
        // 图片状态
        isLoaded: isLoaded,                    // 是否已加载
        isLoading: isLoading,                   // 是否正在加载
        hasError: hasError,                    // 是否有错误
        isCompressing: isCompressing,          // 是否正在压缩
        
        // 优化信息（如果已获取）
        optimizationInfo: optimizationInfoRef.current,
        
        // 图片元素引用
        imageElement: event.target,            // 图片DOM元素
      };
      
      onClick(event, imageInfo);
    }
  };

  // 监听 shouldLoad 变化，先检查缓存，如果CDN不支持优化，尝试浏览器端压缩
  useEffect(() => {
    if (shouldLoad && !isLoaded && !hasError && !isLoading && !isCompressing && !cachedBlobUrl && src) {
      // 先尝试从缓存加载
      const loadFromCache = async () => {
        try {
          const finalUrl = getOptimizedUrl(src);
          const blobUrl = await loadImageWithCache(finalUrl);
          if (blobUrl) {
            setCachedBlobUrl(blobUrl);
            cachedBlobUrlRef.current = blobUrl;
            // 从缓存加载时，不设置 isLoading，让图片自然加载
            // 图片加载完成后会触发 onLoad 事件，自动设置 isLoaded 和 isLoading(false)
            return true;
          }
        } catch (error) {
          // 缓存加载失败，继续正常流程
        }
        return false;
      };
      
      loadFromCache().then((fromCache) => {
        if (!fromCache) {
          // 检查是否支持CDN优化，如果不支持且允许浏览器端压缩，则进行压缩
          const cdn = detectCDN(src);
          const shouldUseBrowserCompression = 
            enableBrowserCompression && // 允许浏览器端压缩
            !cdn && // 不支持CDN
            optimize && Object.keys(optimize).length > 0 && // 有优化配置
            typeof window !== 'undefined' && // 浏览器环境
            !compressedSrc; // 还没压缩过
          
          if (shouldUseBrowserCompression) {
            setIsCompressing(true);
            compressImageInBrowser(src, {
              maxWidth: optimize.width || null,
              maxHeight: optimize.height || null,
              quality: optimize.quality ? optimize.quality / 100 : 0.8,
              compressionLevel: optimize.compressionLevel !== undefined ? optimize.compressionLevel : 0,
              blur: optimize.blur !== undefined ? optimize.blur : 0,
              smooth: optimize.smooth !== undefined ? optimize.smooth : true,
              format: optimize.format || null,
            })
              .then((dataURL) => {
                setCompressedSrc(dataURL);
                setIsCompressing(false);
                
                // 计算压缩效果
                const blob = dataURLToBlob(dataURL);
                // console.log('✅ 已启用浏览器端压缩');
                // console.log(`压缩后大小: ${formatFileSize(blob.size)}`);
              })
              .catch((error) => {
                console.warn('浏览器端压缩失败，使用原始URL:', error);
                setIsCompressing(false);
              });
          } else {
            // 如果不需要浏览器端压缩，正常设置加载状态
            setIsLoading(true);
          }
        }
      });
    }
  }, [shouldLoad, isLoaded, hasError, isLoading, isCompressing, src, optimize, compressedSrc, cachedBlobUrl, enableBrowserCompression]);

  // 监听 src 变化
  useEffect(() => {
    // 清理之前的 Blob URL
    if (cachedBlobUrlRef.current) {
      URL.revokeObjectURL(cachedBlobUrlRef.current);
      cachedBlobUrlRef.current = null;
    }
    
    setIsLoaded(false);
    setHasError(false);
    setIsLoading(false);
    setLockedSrc('');
    setCompressedSrc(null); // 重置压缩图片
    setIsCompressing(false);
    setCachedBlobUrl(null); // 重置缓存 Blob URL
    optimizationInfoRef.current = null; // 重置优化信息
    
    if (immediate) {
      setShouldLoad(true);
    } else {
      initObserver();
    }
  }, [src]);

  // 组件挂载
  useEffect(() => {
    if (!immediate) {
      initObserver();
    } else {
      setShouldLoad(true);
    }

    return () => {
      if (observerRef.current) {
        observerRef.current.disconnect();
        observerRef.current = null;
      }
      // 清理 Blob URL
      if (cachedBlobUrlRef.current) {
        URL.revokeObjectURL(cachedBlobUrlRef.current);
        cachedBlobUrlRef.current = null;
      }
    };
  }, []);

  const containerStyle = {
    width: typeof width === 'number' ? `${width}px` : width,
    height: typeof height === 'number' ? `${height}px` : height,
  };

  return (
    <div
      ref={containerRef}
      className={`image-optimize-container ${className}`.trim()}
      style={containerStyle}
    >
      {/* 占位符 */}
      {!isLoaded && !hasError && !isLoading && !cachedBlobUrl && (
        <div className="image-optimize-placeholder">
          {showPlaceholderIcon && (
            <svg
              className="image-optimize-placeholder-icon"
              width="24"
              height="24"
              viewBox="0 0 24 24"
              fill="none"
              xmlns="http://www.w3.org/2000/svg"
            >
              <path
                d="M19 3H5C3.9 3 3 3.9 3 5V19C3 20.1 3.9 21 5 21H19C20.1 21 21 20.1 21 19V5C21 3.9 20.1 3 19 3ZM19 19H5V5H19V19ZM13.96 12.29L11.21 15.83L9.25 13.47L6.5 17H17.5L13.96 12.29Z"
                fill="currentColor"
              />
            </svg>
          )}
        </div>
      )}

      {/* 加载中 */}
      {(isLoading || isCompressing) && !hasError && !cachedBlobUrl && (
        <div className="image-optimize-loading">
          <svg
            className="image-optimize-loading-icon"
            width="24"
            height="24"
            viewBox="0 0 24 24"
            fill="none"
            xmlns="http://www.w3.org/2000/svg"
          >
            <circle
              cx="12"
              cy="12"
              r="10"
              stroke="currentColor"
              strokeWidth="2"
              fill="none"
              strokeDasharray="62.83"
              strokeDashoffset="31.42"
            />
          </svg>
          {isCompressing && (
            <span style={{ marginTop: '8px', fontSize: '12px', color: '#666' }}>
              正在压缩图片...
            </span>
          )}
        </div>
      )}

      {/* 实际图片 */}
      {shouldLoad && optimizedSrc && (
        <img
          ref={imgRef}
          src={optimizedSrc}
          alt={alt}
          data-id={dataId}
          className={`image-optimize-image ${imageClassName}`.trim()}
          style={{
            display: isLoaded || cachedBlobUrl || (!hasError && optimizedSrc) ? 'block' : 'none',
            ...imageStyle,
          }}
          onLoad={handleLoad}
          onError={handleError}
          onClick={handleClick}
        />
      )}

      {/* 错误占位符 */}
      {hasError && (
        <div className="image-optimize-error">
          <svg
            className="image-optimize-error-icon"
            width="24"
            height="24"
            viewBox="0 0 24 24"
            fill="none"
            xmlns="http://www.w3.org/2000/svg"
          >
            <path
              d="M19 3H5C3.9 3 3 3.9 3 5V19C3 20.1 3.9 21 5 21H19C20.1 21 21 20.1 21 19V5C21 3.9 20.1 3 19 3ZM19 19H5V5H19V19Z"
              fill="currentColor"
            />
          </svg>
          {showErrorMessage && (
            <span className="image-optimize-error-text">加载失败</span>
          )}
        </div>
      )}
    </div>
  );
}
